---
variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: "none"
  GET_SOURCES_ATTEMPTS: "3"
  DEFAULT_CI_IMAGE: registry.digital.mephi.ru:5000/lab-oop
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

default:
  image: $DEFAULT_CI_IMAGE
  cache:
    paths:
      - .cache/pip

stages:
  - lint

ruff:
  stage: lint
  script:
    - ruff check . --extend-select=ALL
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

  tags:
    - shared

black:
  stage: lint
  script:
    - black --check .
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  tags:
    - shared

isort:
  stage: lint
  script:
    - isort . --check-only --diff --profile=black
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  tags:
    - shared

pylint:
  stage: lint
  script:
    - pylint .
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  tags:
    - shared

mypy:
  stage: lint
  script:
    - mypy .
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  tags:
    - shared
