[tool.poetry]
name = "another opera"
version = "0.1.0"
description = ""
authors = ["Ivan Boyarintsev <boyarivan06@gmail.com>"]
readme = "README.md"
packages = [
    {include = "funcs"},
]
repository = "https://gitlab.digital.mephi.ru/boyarivan06/another-opera.git"

[tool.poetry.dependencies]
python = "^3.13"
python-dotenv = "^1.0.1"
prompt = "^0.4.1"
pyqt5 = "^5.15.11"
sqlalchemy = "^2.0.38"
audioread = "^3.0.1"
standard-aifc = "^3.13.0"
standard-sunau = "^3.13.0"
pytelegrambotapi = "^4.26.0"


[tool.poetry.group.dev.dependencies]
ruff = "^0.9.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
# Максимальная длина строки
line-length = 88

# Выбор категорий ошибок
lint.select = ["E", "F", "W"]

# Игнорируемые ошибки.poe
# Используйте # noqa: <код ошибки> для исключения конкретных строк.
lint.ignore = []

# Исключенные директории
exclude = [".git", "__pycache__", "venv", ".venv"]

[tool.poetry.scripts]
project = "funcs.scripts.main:main"
bot = "funcs.scripts.bot:main"